use_frameworks!

platform :ios, '10.0'

def common_pods
    pod 'AMKExtensions', :path => '../'
    
    # UI
    pod 'SnapKit'
    pod 'AMKStackView'
    pod 'FDFullscreenPopGesture'
    
    # 网络
    pod 'Alamofire'
    
    # 数据
    pod 'SwiftyJSON' #'JSONKit'
    pod 'HandyJSON'
    
    # 日志
    pod 'SwiftyBeaver'
    #pod 'TinyConsole'
    
    # 调试
    pod 'FLEX'
end

target 'AMKExtensions_Example' do
    common_pods
    target 'AMKExtensions_Tests' do
        inherit! :search_paths
    end
end

target 'Weixin' do
    common_pods
end

target 'Tester' do
    common_pods
end
