use_frameworks!

platform :ios, '10.0'

target 'AMKExtensions_Example' do
    pod 'AMKExtensions', :path => '../'
    pod 'SnapKit'
    pod 'AMKStackView'
    pod 'FLEX'
    #pod 'JSONKit'
    pod 'HandyJSON'

    target 'AMKExtensions_Tests' do
        inherit! :search_paths
    end
end
